pull
js-tasks-ru/vue-20230905_qsdwy1 pull request #6
Opened 2023-10-18 19:53 UTC by qsde1

2023-10-18 19:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-18 19:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-18 20:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-18 20:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-18 20:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-18 20:42 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-18 20:45 UTC, qsde1 commented
очень странное требование с <time :datetime="...">, пришлось писать отдельный computed для этого атрибута

2023-10-18 21:13 UTC, ShGKme commented
> Очень странное требование для time :datetime="..." в 04-MeetupInfo,

Это требование не задачи, а HTML: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time#a_valid_date_string

Этот формат не случайный, это основной международный формат текстового представления даты в ISO ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)).



> ишлось писать отдельный computed, переворачивающий через array.revers() дату и заменяющий '/' на '-', используя locale en-GB, для этого атрибута. Не смог найти нужную локаль. Локально тесты проходили, а в гите нет.

Это не локаль какой-то страны, а именно международный стандарт.

В JS у даты его можно получить методов `toISOString()`. Так как нужна только дата, то затем взять первые 10 символов (после идёт время).

`date.toISOString().substr(0, 10)`

2023-10-18 21:17 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +    }
`required: true` и `default` обычно не нужны одновременно. `required: true` означает, что пропс обязательно должен быть передан. А `default` нужен, чтобы определять значение непереданного пропса (который передавать обязательно).

А вот тип обычно лучше указывать

2023-10-18 21:17 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button type="button" @click='$emit("update:count",count+1)'>{{count}}</button>`,
У текстовой интерполяции принято добавлять пробелы `{{ count }}`. Также и обособлять пробелами операторы и ставить пробел после запятой `@click="$emit("update:count", count + 1)"`

2023-10-18 21:17 UTC, ShGKme commented on 02-components/03-MeetupCover/components/MeetupCover.js
> +    <div class="meetup-cover" :style="[image ? {'--bg-url': 'url(' + image + ')'} : '']">
Здесь можно не оборачивать в массив, так как значение всегда одно

2023-10-18 21:17 UTC, ShGKme commented on 02-components/04-MeetupInfo/components/MeetupInfo.js
> +    getDateForDateTime(){
Вычисляемые свойства - это свойства, значение которых Vue будет реактивно вычислять сам, используя описанную нами функцию вычисления значения. Но это свойство, и именовать её принято, как свойство, а не как функцию (не глаголом, не с get).

2023-10-18 21:17 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +        <UiAlert>Test Error</UiAlert> <!-- вместо 'error' указал 'Test Error' чтобы тест прошел -->
Текстовое сообщение в ошибке можно получить из свойства ошибки message: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message

Сам объект ошибки приходит аргументом в коллбек, переданный в `catch`

2023-10-18 23:19 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-24 22:37 UTC, ShGKme requested changes

2023-10-24 22:37 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button type="button" @click='$emit("update:count", count + 1 | 0)'>{{ count | 0 }}</button>`,
Оператор `|` - это не "ИЛИ", а "побитовое или". Например, 1 | 2 = 3, 2 | 3 = 3.

Или - `||`. Но в этом случае `count + 1 || 0` не имел бы смысла, так как `count + 1` всегда больше нуля при отсутствии значения. Оно будет ложным только при значении 0, которое нет смысла менять на 0

2023-10-24 22:37 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button type="button" @click='$emit("update:count", count + 1 | 0)'>{{ count | 0 }}</button>`,
Но в любом случае, значение по умолчанию должно описываться в описании параметра, а не в каждом месте, где есть вычисления с параметром.

2023-10-29 16:07 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-29 16:14 UTC, qsde1 commented
02-components еще не исправлял, сделал задание из следующей темы 03-sfc

2023-10-29 20:20 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +<style scoped setup>
`setup` - это атрибут блока `<script>` для описания компонента в Composition API с использованием синтаксиса SFC Setup. Его нет у стилей.

2023-10-29 20:20 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +}
Этот стиль не работает, так как `:root` - не элемент этого компонента. Кроме того, он переопределяет уже существующую переменную с корректным значением в глобальных стилях всего приложения.

Переопределять это переменную не нужно, только использовать её, как фон по умолчанию.

2023-10-29 20:20 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +    }
Часть с `linear-gradient` можно не переносить в вычисления в JS, она статичная и всегда есть как фон. Динамически можно вычислять только второй фон

2023-10-30 08:35 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-31 00:27 UTC, ShGKme commented
Обновления приняты, но осталась одна по задаче `02-components/01-CounterButtonComponent/`

2023-11-03 16:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-03 16:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-03 16:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-11-03 17:00 UTC, qsde1 commented
В задании "01-CounterButtonApp" вернул свойство default:0 в обязательный prop.

2024-01-21 12:55 UTC, closed without merging